version: "3"

services:
  postgres:
    image: bitnami/postgresql:11
    container_name: local_db
    environment:
      - POSTGRESQL_USERNAME=local_dev
      - POSTGRESQL_PASSWORD=local_dev
      - POSTGRESQL_DATABASE=local_db
    ports:
      - 5432:5432
    volumes:
      - local_db_data:/bitnami/postgresql
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "email@email.com"
      PGADMIN_DEFAULT_PASSWORD: "password"
    ports:
      - 16543:80
    depends_on:
      - postgres

volumes:
  local_db_data:
