version: "3.7"

services:
  api:
    build:
      context: .
      args:
        - NODE_ENV=development
    volumes:
      - .:/opt/node_app/app:delegated
      - ./package.json:/opt/node_app/package.json
      - notused:/opt/node_app/app/node_modules
    ports:
      - 3000:3000
      - 9229:9229
    command: npm run start:dev
    environment:
      - NODE_ENV=development
    networks:
      - backend
    depends_on:
      - mongo
  mongo:
    image: bitnami/mongodb:4.2
    volumes:
      - api_db_data:/data/db
    environment:
      - MONGODB_USERNAME=mongo
      - MONGODB_PASSWORD=mongo
      - MONGODB_DATABASE=database
    ports:
      - 27017
    networks:
      - backend
networks:
  backend:
volumes:
  api_db_data:
  notused:
